function EEG = sim_simvar(varargin)

g = arg_define([0 Inf],varargin,...
    arg({'srate','SamplingRate'},100,[1 Inf],'Sampling rate (Hz)'), ...
    arg({'Nl','TrialLength'},500,[1 Inf],'Trial length in samples'), ...
    arg({'Nr','NumTrials'},100,'Number of trials (realizations)'), ...
    arg({'ndisc','BurnInSamples'},1000,[0 Inf],'Burn-in samples. Number of initial simulated samples to discard'), ...
    arg({'morder','ModelOrder'},2,[0 Inf],'Model Order'), ...
    arg({'expr','SystemEquations'},


SamplingRate = 100;      % Hz
Nl = 500;                % length of each epoch (samples)
Nr = 100;                % number of trials (realisations)
ndisc = 1000;            % number of samples to discard from VAR model (startup transients)
ModelOrder = 2;          % VAR model order
 
expr = {...
    'x1(t) = 0.6*x1(t-1) +  0.65*x2(t-2)+ e1(t)' ... 
    'x2(t) = 0.5*x2(t-1) + -0.3*x2(t-2) + e2(t)' ...
};

% create prototype VAR structure
Aproto = sim_genVARModelFromEq(expr,ModelOrder);