function [w, A, C, sbc, fpe, th]=mvar_arfit(varargin)
% wrapper function for arfit

verb = arg_extract(varargin,{'verb','Verbosity'},[],0);

g = arg_define([0 1],varargin, ...
            arg_norep({'data','Data'},mandatory), ...
            arg({'morder','ModelOrder','p','pmax'},10,[],'Maximum model order'), ...
            arg({'selector','OrderSelector'},'sbc',{'sbc','fpe'},'Model order selection criterion'), ...
            arg({'verb','Verbosity'},verb,[],'Verbose output'), ...
            arg({'no_const','NoConstantTerm'},true,[],'Exclude constant term in model. Setting this implicitly assumes the process mean is zero.') ...
            );

arg_toworkspace(g);
        
% evaluate the subfunction
[w, A, C, sbc, fpe, th]=arfit(data, morder, morder, selector, fastif(no_const,'zero',''));
