function g = onl_MetaCtrlPnlMiscOpts(varargin)

g = arg_define(0,varargin,...
        arg({'dispBenchmark','DisplayBenchmarking'},false,[],'Display Benchmarking','type','logical'), ...
        arg({'winLenSec','DataWindowLength'},2,[eps 100],'EEG chunk size (sec)'), ...
        arg_subtoggle({'doSIFT','RunSIFT'},[], ...
        {...
            arg({'channelSubset','ChannelSubset'},[], [], 'Cell array of channel names to retain.','type','cellstr','shape','row'), ...
            arg({'dispSpectrum','DisplaySpectrum'},false,[],'Display Spectral Density'), ...
            arg_subtoggle({'dispBrainMovie','DisplayBrainMovie'},[],...
            { ...
                arg({'adaptBrainMovieLimits','AdaptBrainMovieLimits'},true,[],'Adapt Color and Edge Scaling of Brainmovie 3D'), ...
            }, ...
            'Display BrainMovie3D') ...
        },'Enable Source Information Flow Toolbox'));