function testthis(varargin)

arg_define(varargin,...
    arg_norep({'signal','Signal'}), ...
    arg_subswitch({'rep','Representation'},'power', ...
        {'complex',{},'power',{},'logpower',{},'amplitude',{},'phase',{},'polar',{}, ...
         'welch',{arg({'wndlen','WindowLength'},0.25,[],'Window length. Spectral density is estimated in overlapped windows of this length, and then averaged. If this is a fraction, it is implicitly multiplied by the epoch length.'),...
                  arg({'noverlap','Overlapping'},[],[],'Overlap samples. Number of samples by which windows overlap. By default, this is 50% of the window length.'), ...
                  arg({'nfft','FFTLength'},[],[],'Number of FFT bins. Larger numbers give a smoother spectrum.')}, ...
         'multitaper',{arg({'bandwidth','TimeBandwidth'},3,[],'Spectral smoothing. Controls the bias vs. variance of the spectral estimation. Reasonable values are 1 to 3 (1 being fairly noisy, and 3 being fairly smooth but 5x slower)'), ...
                       arg({'tapers','Tapers'},[],[],'Number of tapers. Should be an integer smaller than 2*TimeBandwith; default 2*TimeBandwidth-1'), ...
                       arg({'padding','Padding'},0,[],'FFT padding factor. Controls the oversampling of the spectrum; 0 is the next largest power of two, 1 is 2x as much, etc.')} ...
        }, 'Spectral representation of the signal. Complex and polar are complete representations, the others extract some aspect of the signal. Complex is the only one that usually requires a strong non-linear classifier. Welch and Multitaper are higher-quality spectral estimation techniques. Note: Welch is very slow, be sure to test online performance before relying on it.'),...
    arg({'normalized','Normalized'}, true, [], 'Normalize the spectrum by 1/f. Doing this has benefits for classifiers that work best with naturally normalized features (e.g. some regularized classifiers).'), ...
    arg({'logtransform','LogTransform'}, false, [], 'Log-Transform. Whether to transform the resulting spectral data into the log domain; can facilitates the use of simple (linear) classifiers.'), ...    
    arg({'logspacing','LogSpacing'}, 0, [], 'Log-Spacing. Whether to sub-sample the data in the log domain. If this is a number (>1) it determines the number of samples taken. If this is a fractional number < 1, it is a fraction of the number of trials.'));
