
% get the handle to the brain axis
hbrain = findobj(gcf,'tag','brain1');

%% get the lights
hlights = findobj(hbrain,'type','light');

%% delete all lights in current axis
delete(hlights)

%% place lights opposite camera
camlight headlight

%% find all the nodes/edge objects
hgraph = findobj(hbrain,'tag','tmpmov');

%% find the lonimesh surface
hloni = findobj(hbrain,'tag','lonimesh');

%% find the skull mesh surface
hskull = findobj(hbrain,'tag','skullmesh');


%% set the lighting properties of the nodes/edges
set(hgraph,...
    'AmbientStrength',1, ...
    'DiffuseStrength',1, ...
    'SpecularStrength',1, ...
    'SpecularExponent',25, ...
    'SpecularColorReflectance',0.5);


%% set the lighting properties of the loni mesh
set(hloni,...
    'AmbientStrength',0, ...
    'DiffuseStrength',0.3, ...
    'SpecularStrength',0.9, ...
    'SpecularExponent',10, ...
    'SpecularColorReflectance',0.2, ...
    'FaceAlpha',0.6);

% shiny
% set(hloni,...
%     'AmbientStrength',0.3, ...
%     'DiffuseStrength',0.6, ...
%     'SpecularStrength',0.9, ...
%     'SpecularExponent',10, ...
%     'SpecularColorReflectance',0.4);

%% set the lighting properties of the skull
% set(hskull,...
%     'AmbientStrength',0.8, ...
%     'DiffuseStrength',0, ...
%     'SpecularStrength',1, ...
%     'SpecularExponent',25, ...
%     'SpecularColorReflectance',1, ...
%     'FaceAlpha',0.05,'FaceColor',[1,0.8,0.8]);


% lighter version
set(hskull,...
    'AmbientStrength',0.2, ...
    'DiffuseStrength',1, ...
    'SpecularStrength',1, ...
    'SpecularExponent',25, ...
    'SpecularColorReflectance',1, ...
    'FaceAlpha',0.08,'FaceColor',[1,0.75,0.65]);

%% get figure background
hbg = findobj(gcf,'tag','figureBackground');
try, set(get(hbg,'children'),'facecolor','w'); catch; end
%%

allMaterials={  %ambient    diffuse     specular    specu expnt     specu color refle
    'Shiny',	0.3,        0.6,        0.9,        20,             1.0
    'Dull',		0.3,        0.8,        0.0,        10,             1.0
    'Metal',	0.3,        0.3,        1.0,        25,             .5
    'Default',	'default','default','default','default','default'
};